/// French strings for the live stream component.
const Map<String, String> ismLiveStringsFr = {
  'timeoutError':
      'Oups ! La requête a pris trop de temps. Vérifiez votre connexion Internet et réessayez. Si le problème persiste, contactez notre équipe d\'assistance.',
  'somethingWentWrong':
      'Oups ! Une erreur s\'est produite. Vérifiez votre connexion Internet et réessayez.',
  'noInternet':
      'Pas de connexion Internet. Connectez-vous à Internet et réessayez.',
  'errorLoadingImage': 'Erreur lors du chargement de l\'image',
  'title': 'Diffusions en direct',
  'noStreams': 'Aucune diffusion',
  'all': 'Tout',
  'live': 'En direct',
  'viewAll': 'Voir tout',
  'liveStreams': 'Diffusions en direct',
  'credit': 'Crédit',
  'debit': 'Débit',
  'audioOnly': 'Audio uniquement',
  'scheduled': 'Diffusions programmées',
  'multiLive': 'Multi direct',
  'pk': 'pk',
  'private': 'Privé',
  'ecommerce': 'E-commerce',
  'reStream': 'Rediffusion',
  'hd': 'HD',
  'recorded': 'Enregistré',
  'recordings': 'Enregistrements',
  'noRecordings': 'Aucun enregistrement',
  'normal': 'Normal',
  'threeD': '3D',
  'animated': 'Animé',
  'copublisherRequests': 'Demandes',
  'users': 'Utilisateurs',
  'members': 'Membres',
  'onlineList': 'Liste en ligne',
  'inviteList': 'Liste d\'invitations',
  'audiencelist': 'Liste du public',
  'contributionRanking': 'Classement des contributions',
  'youreLive': 'Vous êtes en direct',
  'preparingYourStream': 'Préparation de votre diffusion',
  'reconnecting': 'Reconnexion... Veuillez patienter',
  'joiningLiveStream': 'Connexion à la diffusion en direct',
  'connectingToLiveStream': 'Connexion à la diffusion en direct...',
  'enablingYourVideo': 'Activation de votre vidéo',
  'pkMessage': 'Le pk commence',
  'uploadingImage': 'Téléchargement de l\'image',
  'youAreLiveNow': 'Vous êtes en direct',
  'tvContinue': 'Continuer',
  'areYouSureEndStream':
      'Êtes-vous sûr de vouloir terminer votre diffusion en direct ?',
  'areYouSureLeaveStream': 'Êtes-vous sûr ?',
  'kickoutMessage':
      'L\'hôte vous a retiré de la diffusion, vous pouvez regarder d\'autres vidéos en direct',
  'streamEnded':
      'L\'hôte a terminé la diffusion que vous regardiez, mais ne vous inquiétez pas ! Vous pouvez consulter d\'autres vidéos en direct',
  'addedModerator':
      '@name vous a ajouté comme modérateur dans une diffusion',
  'attention': 'Attention',
  'requestCopublishingTitle':
      'Demander à participer à cette vidéo en direct',
  'requestCopublishingDescription':
      'Tout le monde peut regarder, certains de vos abonnés peuvent être notifiés. La vidéo peut être enregistrée et apparaître sur le profil.',
  'moderationWarning':
      'Nous modérons les diffusions en direct. Fumer, vulgarité, pornographie, exposition indécente et pédopornographie sont interdits et entraîneront un bannissement. Les diffusions sont surveillées 24h/24.\nAvertissement : Les recharges tierces peuvent entraîner la fermeture, la suspension ou le bannissement permanent du compte.',
  'weSentNotificationToFollowersText':
      'Nous avons envoyé une notification à vos abonnés. Vos fans rejoindront bientôt la diffusion',
  'broadcastingRulesTitle':
      '📢 Règles et réglementations de diffusion',
  'viewerConductTitle': '🛑 Comportement des spectateurs',
  'welcomeToStreamRulesText':
      'Bienvenue sur la diffusion ! Pour garantir une expérience sûre, respectueuse et agréable pour tous, veuillez suivre ces règles :',
  'broadcastingRulesText':
      '18+ uniquement : Cette diffusion est strictement réservée aux adultes (18+). La discrétion du spectateur est conseillée. Respectez les autres : Pas de discours haineux, de harcèlement ou de langage discriminatoire.',
  'noSpammingText':
      'Pas de spam : Évitez de spammer le chat ou de promouvoir du contenu non lié.',
  'hostAcceptedCopublishRequestTitle':
      '@name a accepté votre demande de rejoindre en tant que co-diffuseur',
  'youAreNowACopublisher': 'Vous êtes maintenant co-diffuseur',
  'youCanJoinTheLiveStreamAndStartPublishingYourVideo':
      'Vous pouvez rejoindre la diffusion en direct et commencer à publier votre vidéo.',
  'hostAcceptedCopublishRequestDescription':
      'Vous pouvez maintenant rejoindre la vidéo en direct en tant que co-diffuseur et commencer à publier',
  'pleaseSelectCoverPhoto':
      'Veuillez sélectionner une photo de couverture pour passer en direct',
  'tapAgainToExit': 'Appuyez à nouveau pour quitter',
  'takePhoto': 'Prendre une photo',
  'chooseFromGallery': 'Choisir dans la galerie',
  'addedToModeratorGroupTitle':
      'Ajouté au groupe de modérateurs de la diffusion',
  'addedToModeratorGroupDescription':
      '@moderatorName a été ajouté au groupe de modérateurs de la diffusion par @initiatorName. En tant que modérateur, on peut expulser des membres et des spectateurs, répondre et supprimer des messages',
  'currentlyModeratingTitle':
      'Vous modérez actuellement la diffusion',
  'currentlyModeratingDescription':
      'En tant que modérateur, vous pouvez expulser des membres et des spectateurs, répondre et supprimer des messages.',
  'gotIt': 'Compris',
  'manageModerators': 'Gérer les modérateurs',
  'stopModerating': 'Arrêter la modération',
  'noModerator': 'Aucun modérateur',
  'searchModerators': 'Rechercher des modérateurs',
  'moderators': 'Modérateurs',
  'viewProfile': 'Voir le profil',
  'searchUsers': 'Rechercher des utilisateurs',
  'addModerator': 'Ajouter un modérateur',
  'searchByUsername': 'Rechercher par nom d\'utilisateur',
  'searchRequest': 'Rechercher une demande',
  'noRequestUsers': 'Aucun utilisateur en attente',
  'accepted': 'Accepté',
  'deny': 'Refusé',
  'noUsers': 'Aucun utilisateur',
  'searchUser': 'Rechercher un utilisateur',
  'premiumBroadcast': 'Diffusion premium',
  'setCoinsFromFans':
      'Définissez les pièces que vous souhaitez recevoir de vos fans',
  'enterCoins': 'Entrer les pièces',
  'save': 'Enregistrer',
  'restreamChannel': 'Chaîne de rediffusion',
  'restreamOn': 'Rediffuser sur',
  'enableStreamOn': 'Activer la diffusion sur',
  'rtmlUrl': 'URL RTML',
  'streamKey': 'Clé de diffusion',
  'enterRtmlUrl': 'Entrer l\'URL RTML',
  'enterStreamKey': 'Entrer la clé de diffusion',
  'streamKeyHint':
      'La clé sera générée après le démarrage d\'une nouvelle diffusion',
  'rtmpStreamInstruction':
      'Veuillez copier et coller la CLÉ DE DIFFUSION et l\'URL DE DIFFUSION dans votre appareil de streaming RTMP.',
  'copiedToClipboard': 'Copié dans le presse-papiers',
  'nothingToCopy': 'Rien à copier',
  'youtubeStreamUrlInstruction':
      'Vous devez entrer l\'URL de diffusion YouTube ici,\n',
  'clickHereToKnowMore': 'cliquez ici pour en savoir plus.',
  'scheduleStream': 'Programmer la diffusion',
  'confirm': 'Confirmer',
  'streamSchedule': 'Programme de diffusion',
  'editScheduleStream': 'Modifier la diffusion programmée',
  'scheduleUpdated': 'Programme mis à jour',
  'scheduleUpdatedDescription': 'Votre diffusion sera en direct le',
  'editStream': 'Modifier la diffusion',
  'deleteStream': 'Supprimer la diffusion',
  'liveStreamEnded': 'Diffusion en direct terminée !',
  'liveStream': 'Diffusion en direct',
  'hearts': 'Cœurs',
  'order': 'Commande',
  'viewers': 'Spectateurs',
  'followers': 'Abonnés',
  'earnings': 'Revenus',
  'duration': 'Durée',
  'viewer': 'Spectateur',
  'cancel': 'Annuler',
  'stopStream': 'Arrêter la diffusion',
  'endStream': 'Terminer la diffusion',
  'leaveStream': 'Quitter la diffusion',
  'requestDeniedByHost': 'Demande refusée par l\'hôte',
  'requestedCopublishing': 'Co-diffusion demandée',
  'sendRequest': 'Envoyer la demande',
  'startVideo': 'Démarrer la vidéo',
  'premiumStreamPayToJoinMessage':
      'Cette diffusion est premium. Pour rejoindre, vous devez payer %s pièces',
  'payAndContinue': 'Payer et continuer',
  'exit': 'Quitter',
  'unableToReconnectToYourStream':
      'Impossible de se reconnecter à votre diffusion. Veuillez réessayer ou démarrer une nouvelle diffusion',
  'unableToReconnectToStreamRejoin':
      'Impossible de se reconnecter à la diffusion. Veuillez réessayer ou rejoindre la diffusion',
  'unableToReconnectToStreamBrowseOther':
      'Impossible de se reconnecter à la diffusion. Veuillez réessayer ou parcourir d\'autres diffusions',
  'pkWithFriends': 'PK avec des amis',
  'search': 'rechercher',
  'noDataFound': 'aucune donnée trouvée',
  'invite': 'inviter',
  'accept': 'Accepter',
  'reject': 'Rejeter',
  'pkChallengeSettings': 'Paramètres du défi PK',
  'pkChallengeSettingsDescription':
      'Configurez votre défi PK en modifiant les paramètres ci-dessous',
  'winnerTakesAll': 'Le gagnant remporte tout',
  'winnerTakesAllDescription':
      'Cela transférera tous les cadeaux gagnés par le perdant au gagnant',
  'choosePkChallengeDuration': 'Choisir la durée du défi PK',
  'confirmAndStart': 'Confirmer et démarrer',
  'minShort': 'min',
  'recording': 'Enregistrement',
  'failedToLoadVideo': 'Échec du chargement de la vidéo',
  'retry': 'Réessayer',
  'coinsWallet': 'Portefeuille de pièces',
  'totalCoins': 'Total des pièces',
  'coins': 'Pièces',
  'transactions': 'Transactions',
  'withdraw': 'Retirer',
  'totalMoney': 'Total d\'argent',
  'coinTransactions': 'Transactions de pièces',
  'noData': 'Aucune donnée',
  'transactionId': 'ID de transaction :',
  'breakdown': 'Détail',
  'searchCopublisher': 'Rechercher un co-diffuseur',
  'okay': 'D\'accord',
  'discountPercentage': 'Pourcentage de réduction',
  'enterDiscountPercentage': 'Entrer le pourcentage de réduction',
  'add': 'Ajouter',
  'addProducts': 'Ajouter des produits',
  'noProductsAvailable':
      'Aucun produit disponible à taguer',
  'selected': 'Sélectionné',
  'topViewers': 'Meilleurs spectateurs',
  'noViewers': 'Aucun spectateur',
  'tagProducts': 'Taguer des produits',
  'pinItem': 'Épingler l\'élément',
  'messageOptions': 'Options de message',
  'reply': 'Répondre',
  'delete': 'Supprimer',
  'myBalance': 'Mon solde',
  'addCoins': 'Ajouter des pièces',
  'yes': 'Oui',
  'no': 'Non',
  'camera': 'Caméra',
  'gallery': 'Galerie',
  'video': 'Vidéo',
  'doc': 'Document',
  'turnOffVideo': 'Désactiver la vidéo',
  'turnOnVideo': 'Activer la vidéo',
  'mute': 'Muet',
  'unmute': 'Activer le son',
  'singleMultiGuestLive': 'Direct solo/multi invités',
  'liveFromDevice': 'Direct depuis l\'appareil',
  'today': 'Aujourd\'hui',
  'tomorrow': 'Demain',
  'free': 'Gratuit',
  'premium': 'Premium',
  'facebook': 'Facebook',
  'youtube': 'Youtube',
  'instagram': 'Instagram',
  'goLive': 'Passer en direct',
  'update': 'Mettre à jour',
  'enterDescription': 'Entrer une description',
  'hdBroadcast': 'Diffusion HD',
  'recordBroadcast': 'Enregistrer la diffusion',
  'restreamBroadcast': 'Rediffuser la diffusion',
  'usePersistentRtmpStreamKey': 'Utiliser une clé RTMP persistante',
  'scheduleLive': 'Programmer le direct',
  'coinsCountFormat': '%s pièces',
  'addCover': 'Ajouter une couverture',
  'addProductRequired': 'Ajouter un produit*',
  'addPlus': '+Ajouter',
  'addProductsAction': 'Ajouter des produits',
  'dateAndTimeRequired': 'Date et heure*',
  'persistentRtmpStreamInstruction':
      'Veuillez copier et coller la CLÉ DE DIFFUSION et l\'URL DE DIFFUSION dans votre appareil de streaming RTMP. \nSi vous souhaitez créer une nouvelle clé de diffusion au cas où vous pensez que votre clé est compromise ',
  'clickHere': 'cliquez ici.',
  'enterFieldFormat': 'Entrer %s',
  'errorInitializingCamera': 'Erreur lors de l\'initialisation de la caméra',
  'cameraPermissionTurnedOff':
      'L\'autorisation de la caméra est désactivée.\nVeuillez l\'activer pour continuer.',
  'turnOn': 'Activer',
  'broadcastersUnder18NotPermitted':
      'Les diffuseurs de moins de 18 ans ne sont pas autorisés',
};
