/// Portuguese strings for the live stream component.
const Map<String, String> ismLiveStringsPt = {
  'timeoutError':
      'Ops! A solicitação demorou muito para ser processada. Verifique sua conexão com a Internet e tente novamente. Se o problema persistir, entre em contato com nossa equipe de suporte.',
  'somethingWentWrong':
      'Ops! Algo deu errado. Verifique sua conexão com a Internet e tente novamente.',
  'noInternet':
      'Sem conexão com a Internet. Conecte-se à Internet e tente novamente.',
  'errorLoadingImage': 'Erro ao carregar imagem',
  'title': 'Transmissões ao vivo',
  'noStreams': 'Nenhuma transmissão',
  'all': 'Todos',
  'live': 'Ao vivo',
  'viewAll': 'Ver tudo',
  'liveStreams': 'Transmissões ao vivo',
  'credit': 'Crédito',
  'debit': 'Débito',
  'audioOnly': 'Somente áudio',
  'scheduled': 'Transmissões agendadas',
  'multiLive': 'Multi ao vivo',
  'pk': 'pk',
  'private': 'Privado',
  'ecommerce': 'E-commerce',
  'reStream': 'Retransmissão',
  'hd': 'HD',
  'recorded': 'Gravado',
  'recordings': 'Gravações',
  'noRecordings': 'Nenhuma gravação',
  'normal': 'Normal',
  'threeD': '3D',
  'animated': 'Animado',
  'copublisherRequests': 'Solicitações',
  'users': 'Usuários',
  'members': 'Membros',
  'onlineList': 'Lista online',
  'inviteList': 'Lista de convites',
  'audiencelist': 'Lista de audiência',
  'contributionRanking': 'Ranking de contribuições',
  'youreLive': 'Você está ao vivo',
  'preparingYourStream': 'Preparando sua transmissão',
  'reconnecting': 'Reconectando... Aguarde',
  'joiningLiveStream': 'Entrando na transmissão ao vivo',
  'connectingToLiveStream': 'Conectando à transmissão ao vivo...',
  'enablingYourVideo': 'Ativando seu vídeo',
  'pkMessage': 'pk está começando',
  'uploadingImage': 'Enviando imagem',
  'youAreLiveNow': 'Você está ao vivo',
  'tvContinue': 'Continuar',
  'areYouSureEndStream':
      'Tem certeza de que deseja encerrar sua transmissão ao vivo?',
  'areYouSureLeaveStream': 'Tem certeza?',
  'kickoutMessage':
      'O anfitrião removeu você da transmissão, você pode assistir outros vídeos ao vivo',
  'streamEnded':
      'O anfitrião encerrou a transmissão que você estava assistindo, mas não se preocupe! Você pode conferir outros vídeos ao vivo',
  'addedModerator':
      '@name adicionou você como moderador em uma transmissão',
  'attention': 'Atenção',
  'requestCopublishingTitle':
      'Solicitar participação neste vídeo ao vivo',
  'requestCopublishingDescription':
      'Qualquer pessoa pode assistir, alguns dos seus seguidores podem ser notificados. O vídeo pode ser salvo e aparecer no perfil.',
  'moderationWarning':
      'Moderamos transmissões ao vivo. Fumar, vulgaridade, pornografia, exposição indecente e pornografia infantil não são permitidos e resultarão em banimento. As transmissões são monitoradas 24 horas por dia.\nAviso: Recarga de terceiros pode resultar em encerramento, suspensão ou banimento permanente da conta.',
  'weSentNotificationToFollowersText':
      'Enviamos uma notificação aos seus seguidores. Seus fãs entrarão na transmissão em breve',
  'broadcastingRulesTitle':
      '📢 Regras e regulamentos de transmissão',
  'viewerConductTitle': '🛑 Conduta do espectador',
  'welcomeToStreamRulesText':
      'Bem-vindo à transmissão! Para garantir uma experiência segura, respeitosa e agradável para todos, siga estas regras:',
  'broadcastingRulesText':
      'Apenas 18+: Esta transmissão é estritamente para adultos (18+). Discrição do espectador é aconselhada. Respeite os outros: Sem discurso de ódio, assédio ou linguagem discriminatória.',
  'noSpammingText':
      'Sem spam: Evite spammar o chat ou promover conteúdo não relacionado.',
  'hostAcceptedCopublishRequestTitle':
      '@name aceitou sua solicitação para participar como co-transmissor',
  'youAreNowACopublisher': 'Você agora é co-transmissor',
  'youCanJoinTheLiveStreamAndStartPublishingYourVideo':
      'Você pode entrar na transmissão ao vivo e começar a publicar seu vídeo.',
  'hostAcceptedCopublishRequestDescription':
      'Agora você pode entrar no vídeo ao vivo como co-transmissor e começar a publicar',
  'pleaseSelectCoverPhoto':
      'Selecione uma foto de capa para ir ao vivo',
  'tapAgainToExit': 'Toque novamente para sair',
  'takePhoto': 'Tirar foto',
  'chooseFromGallery': 'Escolher da galeria',
  'addedToModeratorGroupTitle':
      'Adicionado ao grupo de moderadores da transmissão',
  'addedToModeratorGroupDescription':
      '@moderatorName foi adicionado ao grupo de moderadores da transmissão por @initiatorName. Como moderador, pode expulsar membros e espectadores, responder e excluir mensagens',
  'currentlyModeratingTitle':
      'Você está moderando a transmissão',
  'currentlyModeratingDescription':
      'Como moderador, você pode expulsar membros e espectadores, responder e excluir mensagens.',
  'gotIt': 'Entendi',
  'manageModerators': 'Gerenciar moderadores',
  'stopModerating': 'Parar de moderar',
  'noModerator': 'Nenhum moderador',
  'searchModerators': 'Buscar moderadores',
  'moderators': 'Moderadores',
  'viewProfile': 'Ver perfil',
  'searchUsers': 'Buscar usuários',
  'addModerator': 'Adicionar moderador',
  'searchByUsername': 'Buscar por nome de usuário',
  'searchRequest': 'Buscar solicitação',
  'noRequestUsers': 'Nenhum usuário solicitante',
  'accepted': 'Aceito',
  'deny': 'Negado',
  'noUsers': 'Nenhum usuário',
  'searchUser': 'Buscar usuário',
  'premiumBroadcast': 'Transmissão premium',
  'setCoinsFromFans':
      'Defina as moedas que deseja receber dos seus fãs',
  'enterCoins': 'Inserir moedas',
  'save': 'Salvar',
  'restreamChannel': 'Canal de retransmissão',
  'restreamOn': 'Retransmitir em',
  'enableStreamOn': 'Ativar transmissão em',
  'rtmlUrl': 'URL RTML',
  'streamKey': 'Chave de transmissão',
  'enterRtmlUrl': 'Inserir URL RTML',
  'enterStreamKey': 'Inserir chave de transmissão',
  'streamKeyHint':
      'A chave será gerada após iniciar uma nova transmissão',
  'rtmpStreamInstruction':
      'Copie e cole a CHAVE DE TRANSMISSÃO e a URL DE TRANSMISSÃO no seu dispositivo de streaming RTMP.',
  'copiedToClipboard': 'Copiado para a área de transferência',
  'nothingToCopy': 'Nada para copiar',
  'youtubeStreamUrlInstruction':
      'Você precisa inserir a URL de transmissão do YouTube aqui,\n',
  'clickHereToKnowMore': 'clique aqui para saber mais.',
  'scheduleStream': 'Agendar transmissão',
  'confirm': 'Confirmar',
  'streamSchedule': 'Agenda de transmissão',
  'editScheduleStream': 'Editar transmissão agendada',
  'scheduleUpdated': 'Agenda atualizada',
  'scheduleUpdatedDescription': 'Sua transmissão ficará ao vivo em',
  'editStream': 'Editar transmissão',
  'deleteStream': 'Excluir transmissão',
  'liveStreamEnded': 'Transmissão ao vivo encerrada!',
  'liveStream': 'Transmissão ao vivo',
  'hearts': 'Corações',
  'order': 'Pedido',
  'viewers': 'Espectadores',
  'followers': 'Seguidores',
  'earnings': 'Ganhos',
  'duration': 'Duração',
  'viewer': 'Espectador',
  'cancel': 'Cancelar',
  'stopStream': 'Parar transmissão',
  'endStream': 'Encerrar transmissão',
  'leaveStream': 'Sair da transmissão',
  'requestDeniedByHost': 'Solicitação negada pelo anfitrião',
  'requestedCopublishing': 'Co-transmissão solicitada',
  'sendRequest': 'Enviar solicitação',
  'startVideo': 'Iniciar vídeo',
  'premiumStreamPayToJoinMessage':
      'Esta transmissão é premium. Para entrar, você precisa pagar %s moedas',
  'payAndContinue': 'Pagar e continuar',
  'exit': 'Sair',
  'unableToReconnectToYourStream':
      'Não foi possível reconectar à sua transmissão. Tente novamente ou inicie uma nova transmissão',
  'unableToReconnectToStreamRejoin':
      'Não foi possível reconectar à transmissão. Tente novamente ou reentre na transmissão',
  'unableToReconnectToStreamBrowseOther':
      'Não foi possível reconectar à transmissão. Tente novamente ou navegue por outras transmissões',
  'pkWithFriends': 'PK com amigos',
  'search': 'buscar',
  'noDataFound': 'nenhum dado encontrado',
  'invite': 'convidar',
  'accept': 'Aceitar',
  'reject': 'Rejeitar',
  'pkChallengeSettings': 'Configurações do desafio PK',
  'pkChallengeSettingsDescription':
      'Configure seu desafio PK modificando as configurações abaixo',
  'winnerTakesAll': 'O vencedor leva tudo',
  'winnerTakesAllDescription':
      'Isso transferirá todos os presentes ganhos pelo perdedor para o vencedor',
  'choosePkChallengeDuration': 'Escolher duração do desafio PK',
  'confirmAndStart': 'Confirmar e iniciar',
  'minShort': 'min',
  'recording': 'Gravação',
  'failedToLoadVideo': 'Falha ao carregar vídeo',
  'retry': 'Tentar novamente',
  'coinsWallet': 'Carteira de moedas',
  'totalCoins': 'Total de moedas',
  'coins': 'Moedas',
  'transactions': 'Transações',
  'withdraw': 'Sacar',
  'totalMoney': 'Total em dinheiro',
  'coinTransactions': 'Transações de moedas',
  'noData': 'Sem dados',
  'transactionId': 'ID da transação:',
  'breakdown': 'Detalhamento',
  'searchCopublisher': 'Buscar co-transmissor',
  'okay': 'Ok',
  'discountPercentage': 'Porcentagem de desconto',
  'enterDiscountPercentage': 'Inserir porcentagem de desconto',
  'add': 'Adicionar',
  'addProducts': 'Adicionar produtos',
  'noProductsAvailable':
      'Não há produtos disponíveis para marcar',
  'selected': 'Selecionado',
  'topViewers': 'Principais espectadores',
  'noViewers': 'Nenhum espectador',
  'tagProducts': 'Marcar produtos',
  'pinItem': 'Fixar item',
  'messageOptions': 'Opções de mensagem',
  'reply': 'Responder',
  'delete': 'Excluir',
  'myBalance': 'Meu saldo',
  'addCoins': 'Adicionar moedas',
  'yes': 'Sim',
  'no': 'Não',
  'camera': 'Câmera',
  'gallery': 'Galeria',
  'video': 'Vídeo',
  'doc': 'Documento',
  'turnOffVideo': 'Desativar vídeo',
  'turnOnVideo': 'Ativar vídeo',
  'mute': 'Mudo',
  'unmute': 'Ativar som',
  'singleMultiGuestLive': 'Ao vivo solo/multi convidados',
  'liveFromDevice': 'Ao vivo do dispositivo',
  'today': 'Hoje',
  'tomorrow': 'Amanhã',
  'free': 'Grátis',
  'premium': 'Premium',
  'facebook': 'Facebook',
  'youtube': 'Youtube',
  'instagram': 'Instagram',
  'goLive': 'Ir ao vivo',
  'update': 'Atualizar',
  'enterDescription': 'Inserir descrição',
  'hdBroadcast': 'Transmissão HD',
  'recordBroadcast': 'Gravar transmissão',
  'restreamBroadcast': 'Retransmitir transmissão',
  'usePersistentRtmpStreamKey': 'Usar chave RTMP persistente',
  'scheduleLive': 'Agendar ao vivo',
  'coinsCountFormat': '%s moedas',
  'addCover': 'Adicionar capa',
  'addProductRequired': 'Adicionar produto*',
  'addPlus': '+Adicionar',
  'addProductsAction': 'Adicionar produtos',
  'dateAndTimeRequired': 'Data e hora*',
  'persistentRtmpStreamInstruction':
      'Copie e cole a CHAVE DE TRANSMISSÃO e a URL DE TRANSMISSÃO no seu dispositivo de streaming RTMP. \nSe quiser criar uma nova chave de transmissão caso ache que sua chave foi comprometida ',
  'clickHere': 'clique aqui.',
  'enterFieldFormat': 'Inserir %s',
  'errorInitializingCamera': 'Erro ao inicializar a câmera',
  'cameraPermissionTurnedOff':
      'A permissão da câmera está desativada.\nAtive-a para continuar.',
  'turnOn': 'Ativar',
  'broadcastersUnder18NotPermitted':
      'Transmitidores menores de 18 anos não são permitidos',
  'settings': 'Configurações',
  'saySomething': 'Diga algo…',
  'success': 'Sucesso',
  'error': 'Erro',
  'stop': 'Parar',
  'end': 'Encerrar',
  'resend': 'Reenviar',
  'report': 'Denunciar',
  'moreOptions': 'Mais opções',
  'kickOut': 'Expulsar',
  'buyNow': 'Comprar agora',
  'addDiscount': 'Adicionar desconto',
  'viewLess': 'Ver menos',
  'viewMore': 'Ver mais',
  'noTimeSet': 'Nenhum horário definido',
  'itsADraw': 'Empate!',
  'congratulationsTo': 'Parabéns para @%s',
  'coinBalance': 'Saldo de moedas',
  'insufficientGiftBalance':
      'Saldo insuficiente para enviar presente\n Adicione moedas à carteira ',
  'noPlayableRecordingUrl':
      'Nenhuma URL de gravação reproduzível para este stream',
  'removeModeratorConfirm':
      'Tem certeza de que deseja remover %s como moderador?',
  'timeoutErrorTitle': 'Erro de tempo esgotado',
  'argumentErrorTitle': 'Erro de argumento',
  'internetErrorTitle': 'Erro de internet',
  'videoFailedToLoad': 'Falha ao carregar o vídeo',
  'tapToRetry': 'Toque para tentar novamente',
  'videoPlayerError': 'Erro do player de vídeo',
  'unableToFetchAccountToken':
      'Não foi possível obter o token da conta. Tente novamente.',
  'myStream': 'Meu stream',
  'atTimeFormat': 'Às %s',
  'cropper': 'Cortar',
  'screenSharing': 'Compartilhamento de tela',
  'screenSharingNotificationText': '%s está compartilhando a tela.',
  'shareStreamText': 'confira meu site https://example.com',
  'replyingToFormat': 'Respondendo a @%s: %s',
  'replyToFormat': 'Responder a %s',
  'hostFallback': 'Anfitrião',
  'userFallback': 'Usuário',
  'changeHost': 'Trocar anfitrião',
  'copublishingRequest': 'Solicitação de co-publicação',
  'copublishingRequested': 'Co-publicação solicitada',
  'copublishingAdded': 'Co-publicação adicionada',
  'hostAcceptedYourCopublishRequest':
      '%s aceitou sua solicitação de co-publicação',
  'youAcceptedCopublishRequest':
      'Você aceitou a solicitação de co-publicação de %s',
  'userRequestedCopublishing': '%s solicitou co-publicação',
  'hostRejectedYourCopublishRequest':
      '%s rejeitou sua solicitação de co-publicação',
  'youRejectedCopublishRequest':
      'Você rejeitou a solicitação de co-publicação de %s',
  'hostAddedYouAsCopublisher': '%s adicionou você como co-publicador',
  'youAddedAsCopublisher': 'Você adicionou %s como co-publicador',
  'hostAddedMemberAsCopublisher': '%s adicionou %s como co-publicador',
  'memberStoppedPublishing': '%s parou de publicar e saiu',
  'isModeratorNow': '%s agora é moderador',
  'leftFromModerator': '%s saiu da moderação ',
  'viewerHasJoined': '%s entrou',
  'viewerHasLeft': '%s saiu',
  'pkRequestRejected': 'Solicitação de PK rejeitada',
  'pkRequested': 'PK solicitado',
  'pkInviteYouToLink': '@%s convida você para vincular',
  'pkInvitationDescription':
      'Você recebeu um convite de @%s para o desafio PK. Deseja continuar?',
  'stopPkBattle': 'Deseja parar a batalha PK',
  'endPk': 'Deseja encerrar o PK',
  'pkChallengeStartingSoon':
      'O desafio PK entre você e %s começará em breve. Aguarde…',
  'linking': 'Vinculando...',
  'deletedMessageFormat': '%s Mensagem excluída',
  'alreadyLiveOnAnotherDevice':
      'Parece que você já está ao vivo em outro dispositivo. Deseja encerrar essa transmissão?',
};
