/// English (default) strings for the live stream component.
const Map<String, String> ismLiveStringsEn = {
  'timeoutError':
      'Oops! The request took too long to process. Please check your internet connection and try again. If the issue persists, you can contact our support team for assistance.',
  'somethingWentWrong':
      'Oops! Something went wrong. Please check your internet connection and try again.',
  'noInternet':
      'No internet connection. Please connect to the internet and try again.',
  'errorLoadingImage': 'Error loading image',
  'title': 'Live Streams',
  'noStreams': 'No Streams',
  'all': 'All',
  'live': 'Live',
  'viewAll': 'View all',
  'liveStreams': 'Live Streams',
  'credit': 'Credit',
  'debit': 'Debit',
  'audioOnly': 'Audio Only',
  'scheduled': 'Scheduled Streams',
  'multiLive': 'Multi Live',
  'pk': 'pk',
  'private': 'Private',
  'ecommerce': 'Ecommerce',
  'reStream': 'Restream',
  'hd': 'HD',
  'recorded': 'Recorded',
  'recordings': 'Recordings',
  'noRecordings': 'No Recordings',
  'normal': 'Normal',
  'threeD': '3D',
  'animated': 'Animated',
  'copublisherRequests': 'Requests',
  'users': 'Users',
  'members': 'Members',
  'onlineList': 'Online List',
  'inviteList': 'InviteList',
  'audiencelist': 'Audience list',
  'contributionRanking': 'Contribution Ranking',
  'youreLive': "You're Live",
  'preparingYourStream': 'Preparing your stream',
  'reconnecting': 'Reconnecting... Please wait',
  'joiningLiveStream': 'Joining the live stream',
  'connectingToLiveStream': 'Connecting to the live stream...',
  'enablingYourVideo': 'Enabling your video',
  'pkMessage': 'pk is starting',
  'uploadingImage': 'Uploading Image',
  'youAreLiveNow': 'You’re Live Now',
  'tvContinue': 'Continue',
  'areYouSureEndStream':
      'Are you sure that you want to end your live stream?',
  'areYouSureLeaveStream': 'Are you sure?',
  'kickoutMessage':
      'The host has removed you from the stream, you can watch other live videos',
  'streamEnded':
      "The host has ended the stream you were watching, but don't worry! You can check out other live videos",
  'addedModerator': '@name has added you as a moderator in a stream',
  'attention': 'Attention',
  'requestCopublishingTitle': 'Request to be in this live video',
  'requestCopublishingDescription':
      "Anyone can watch, some of yours followers may get notified elizabeth can save this to igtv, which means it'll appear on their profile and anywhere else the igtv video shows.",
  'moderationWarning':
      'We moderate live broadcasts. smoking vulgarity, porn,indecent exposure, chid pornograpgy is not allowedand will be banned. live broadcasts are monitored 24 hours a day.\nWarning: Third-party top-up or recharge is subject to account closure, suspension, or permanent ban.',
  'weSentNotificationToFollowersText':
      'We’ve sent a notification to your followers. Your fans will join the broadcast soon',
  'broadcastingRulesTitle': '📢 Broadcasting Rules & Regulations',
  'viewerConductTitle': '🛑 Viewer Conduct',
  'welcomeToStreamRulesText':
      'Welcome to the stream! To ensure a safe, respectful, and enjoyable experience for everyone, please follow these rules:',
  'broadcastingRulesText':
      '18+ Only: This stream is strictly for adults (18+). Viewer discretion is advised. Respect Others: No hate speech, harassment, or discriminatory language.',
  'noSpammingText':
      'No Spamming: Avoid spamming the chat or promoting unrelated content.',
  'hostAcceptedCopublishRequestTitle':
      '@name has accepted your request to join as a co-publisher',
  'youAreNowACopublisher': "You're now a co-publisher",
  'youCanJoinTheLiveStreamAndStartPublishingYourVideo':
      'You can join the live stream and start publishing your video.',
  'hostAcceptedCopublishRequestDescription':
      'You can now join the live video as a co-publisher and start publishing',
  'pleaseSelectCoverPhoto': 'Please select a cover photo to go live',
  'tapAgainToExit': 'Tap again to exit',
  'takePhoto': 'Take photo',
  'chooseFromGallery': 'Choose from gallery',
  'addedToModeratorGroupTitle': "Added to moderator's group of broadcast",
  'addedToModeratorGroupDescription':
      '@moderatorName has been added to the moderator\'s group of broadcast by @initiatorName. Being a moderator one can kick out members and viewers, reply-to and delete messages',
  'currentlyModeratingTitle': "You're currently moderating the broadcast",
  'currentlyModeratingDescription':
      'Being a moderator you can kickout members and viewers, reply to and delete messages.',
  'gotIt': 'Got It',
  'manageModerators': 'Manage Moderators',
  'stopModerating': 'Stop Moderating',
  'noModerator': 'No Moderator',
  'searchModerators': 'Search Moderators',
  'moderators': 'Moderators',
  'viewProfile': 'View Profile',
  'searchUsers': 'Search Users',
  'addModerator': 'Add Moderator',
  'searchByUsername': 'Search by username',
  'searchRequest': 'Search Request',
  'noRequestUsers': 'No request users',
  'accepted': 'Accepted',
  'deny': 'Denied',
  'noUsers': 'No users',
  'searchUser': 'Search User',
  'premiumBroadcast': 'Premium Broadcast',
  'setCoinsFromFans': 'Set coins you want to get from your fans',
  'enterCoins': 'Enter coins',
  'save': 'Save',
  'restreamChannel': 'Restream Channel',
  'restreamOn': 'Restream on',
  'enableStreamOn': 'Enable stream on',
  'rtmlUrl': 'RTML URL',
  'streamKey': 'Stream key',
  'enterRtmlUrl': 'Enter RTML URL',
  'enterStreamKey': 'Enter Stream key',
  'streamKeyHint': 'Key will be generated after you start a new stream',
  'rtmpStreamInstruction':
      'Please copy and paste the STREAM KEY and the STREAM URL into your RTMP streaming device.',
  'copiedToClipboard': 'Copied to clipboard',
  'nothingToCopy': 'Nothing to copy',
  'youtubeStreamUrlInstruction':
      'You have to enter the youtube stream url here,\n',
  'clickHereToKnowMore': 'click here to know more.',
  'scheduleStream': 'Schedule Stream',
  'confirm': 'Confirm',
  'streamSchedule': 'Stream Schedule',
  'editScheduleStream': 'Edit Schedule Stream',
  'scheduleUpdated': 'Schedule Updated',
  'scheduleUpdatedDescription': 'Your stream will go live on',
  'editStream': 'Edit Stream',
  'deleteStream': 'Delete Stream',
  'liveStreamEnded': 'Live stream ended!',
  'liveStream': 'Live stream',
  'hearts': 'Hearts',
  'order': 'Order',
  'viewers': 'Viewers',
  'followers': 'Followers',
  'earnings': 'Earnings',
  'duration': 'Duration',
  'viewer': 'Viewer',
  'cancel': 'Cancel',
  'stopStream': 'Stop stream',
  'endStream': 'End Stream',
  'leaveStream': 'Leave stream',
  'requestDeniedByHost': 'Request denied by the host',
  'requestedCopublishing': 'Requested Co-publishing',
  'sendRequest': 'Send Request',
  'startVideo': 'Start Video',
  'premiumStreamPayToJoinMessage':
      'This stream is premium. To join you need to pay %s coins',
  'payAndContinue': 'Pay & Continue',
  'exit': 'Exit',
  'unableToReconnectToYourStream':
      'Unable to reconnect to your stream. Please try again or start a new stream',
  'unableToReconnectToStreamRejoin':
      'Unable to reconnect to the stream. Please try again or rejoin the stream',
  'unableToReconnectToStreamBrowseOther':
      'Unable to reconnect to the stream. Please try again or browse other streams',
  'pkWithFriends': 'PK With Friends',
  'search': 'search',
  'noDataFound': 'no data found',
  'invite': 'invite',
  'accept': 'Accept',
  'reject': 'Reject',
  'pkChallengeSettings': 'PK Challenge Settings',
  'pkChallengeSettingsDescription':
      'Configure your PK challenge by modifying the settings below',
  'winnerTakesAll': 'Winner takes all',
  'winnerTakesAllDescription':
      'This would transfer all the gifts earned by the looser to the winner',
  'choosePkChallengeDuration': 'Choose PK Challenge Duration',
  'confirmAndStart': 'Confirm & Start',
  'minShort': 'min',
  'recording': 'Recording',
  'failedToLoadVideo': 'Failed to load video',
  'retry': 'Retry',
  'coinsWallet': 'Coins Wallet',
  'totalCoins': 'Total Coins',
  'coins': 'Coins',
  'transactions': 'Transactions',
  'withdraw': 'Withdraw',
  'totalMoney': 'Total Money',
  'coinTransactions': 'Coin Transactions',
  'noData': 'No Data',
  'transactionId': 'TransactionId:',
  'breakdown': 'Breakdown',
  'searchCopublisher': 'Search Copublisher',
  'okay': 'Okay',
  'discountPercentage': 'Discount Percentage',
  'enterDiscountPercentage': 'Enter discount percentage',
  'add': 'Add',
  'addProducts': 'Add Products',
  'noProductsAvailable': 'There are no products available to tag',
  'selected': 'Selected',
  'topViewers': 'Top Viewers',
  'noViewers': 'No Viewers',
  'tagProducts': 'Tag Products',
  'pinItem': 'Pin Item',
  'messageOptions': 'Message Options',
  'reply': 'Reply',
  'delete': 'Delete',
  'myBalance': 'My Balance',
  'addCoins': 'Add Coins',
  'yes': 'Yes',
  'no': 'No',
  'camera': 'Camera',
  'gallery': 'Gallery',
  'video': 'Video',
  'doc': 'Doc',
  'turnOffVideo': 'Turn Off Video',
  'turnOnVideo': 'Trun On Video',
  'mute': 'Mute',
  'unmute': 'Unmute',
  'singleMultiGuestLive': 'Single/Multi Guest Live',
  'liveFromDevice': 'Live From Device',
  'today': 'Today',
  'tomorrow': 'Tomorrow',
  'free': 'Free',
  'premium': 'Premium',
  'facebook': 'Facebook',
  'youtube': 'Youtube',
  'instagram': 'Instagram',
  'goLive': 'Go Live',
  'update': 'Update',
  'enterDescription': 'Enter description',
  'hdBroadcast': 'HD Broadcast',
  'recordBroadcast': 'Record Broadcast',
  'restreamBroadcast': 'Restream Broadcast',
  'usePersistentRtmpStreamKey': 'Use Persistent RTMP Stream Key',
  'scheduleLive': 'Schedule Live',
  'coinsCountFormat': '%s coins',
  'addCover': 'Add Cover',
  'addProductRequired': 'Add product*',
  'addPlus': '+Add',
  'addProductsAction': 'Add products',
  'dateAndTimeRequired': 'Date & Time*',
  'persistentRtmpStreamInstruction':
      'Please copy and paste the STREAM KEY and the STREAM URL into your RTMP streaming device. \nIf you want to create a new stream key in case you think your key is compromised ',
  'clickHere': 'click here.',
  'enterFieldFormat': 'Enter %s',
  'errorInitializingCamera': 'Error while initializing Camera',
  'broadcastersUnder18NotPermitted': 'Broadcasters under 18 are not permitted',
};
