name: appscrip_live_stream_component
description: A new Flutter plugin project.
version: 1.0.0+3
homepage: https://isometrik.io/

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  cached_network_image: ^3.3.1
  camera: ^0.10.5+7
  connectivity_plus: ^6.0.3
  emoji_picker_flutter: ^2.2.0
  file_picker: ^8.0.6
  flutter:
    sdk: flutter
  flutter_background: ^1.2.0
  flutter_local_notifications: ^17.2.1
  flutter_rounded_progress_bar: ^0.3.2
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  flutter_web_plugins:
    sdk: flutter
  get: ^4.6.6
  gif: ^2.3.0
  http: ^1.1.0
  image_cropper: ^7.1.0
  image_picker: ^1.1.2
  in_app_purchase: ^3.2.0
  in_app_purchase_android: ^0.3.6+1
  in_app_purchase_storekit: ^0.3.17
  intl: ^0.19.0
  livekit_client: ^2.2.2
  mqtt_helper: ^1.0.0
  permission_handler: ^11.3.1
  plugin_platform_interface: ^2.1.8
  pull_to_refresh: ^2.0.0
  share_plus: ^10.0.0
  shared_preferences: ^2.2.3
  timezone: ^0.9.2
  wakelock_plus: ^1.2.5

dependency_overrides:
  collection: ^1.19.0
  flutter_webrtc: ^0.11.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.appscrip_live_stream_component
        pluginClass: AppscripLiveStreamComponentPlugin
      ios:
        pluginClass: AppscripLiveStreamComponentPlugin
      web:
        pluginClass: AppscripLiveStreamComponentWeb
        fileName: appscrip_live_stream_component_web.dart
  assets:
    - assets/
    - assets/images/
    - assets/images/gifts/
    - assets/images/gifts/normal/
    - assets/images/gifts/animated/
    - assets/images/gifts/3d/
    - assets/icon/
    - assets/logo/
    - assets/placeholders/
